# Taken from https://github.com/umami-software/umami/blob/master/docker-compose.yml
---
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2
    container_name: umami-app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://${UMAMI_DATABASE_USER}:${UMAMI_DATABASE_PASSWORD}@db:5432/${UMAMI_DATABASE_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_APP_SECRET}
      REDIS_URL: redis://client:P@ssw0rd!@redis:6379
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:17-alpine
    container_name: umami-database
    environment:
      POSTGRES_DB: ${UMAMI_DATABASE_NAME}
      POSTGRES_USER: ${UMAMI_DATABASE_USER}
      POSTGRES_PASSWORD: ${UMAMI_DATABASE_PASSWORD}
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: umami-redis-cache
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: ["/usr/local/etc/redis/redis.conf"]

  example-implementation:
    image: nginx:alpine
    container_name: umami-example-implementation
    volumes:
      - ./example:/usr/share/nginx/html:ro
    ports:
      - ${EXAMPLE_IMPLEMENTATION_PORT}:80
    restart: always
    depends_on:
      umami:
        condition: service_healthy

volumes:
  umami-db-data:
